Repository CMPT-276-SPRING-2025/final-project-11-stars, pull requests merged in 2025-04, with the labels that each got.

#67 feat: make the home page responsive - issue #13
  src/pages/Homepage.css
Labels: enhancement, style

#68 Dark mode #!
  src/pages/Homepage.css
  src/pages/Homepage.js
  src/pages/Quizcategories.css
  src/pages/Quizpage.css
  src/pages/Resultpage.css
Labels: style

#79 style: replaced category icons - issue #13
  public/History.png
  public/Music.png
  public/Science.png
  public/culture.png
  public/culture.svg
  public/custom.svg
  public/custom_quiz.png
  public/film_and_tv.png
  public/film_and_tv.svg
  public/food.png
  public/food.svg
  public/general.png
  public/general_knowledge.svg
  public/geography.png
  public/geography.svg
  public/history.svg
  public/literature.png
  public/literature.svg
  public/music.svg
  public/science.svg
  public/sports.png
  public/sports.svg
  src/pages/Quizcategories.js
Labels: style

#85 Responsive design improvement
  netlify/functions/budEChatbotReply.js
  netlify/functions/generateQuestions.js
  netlify/functions/getFunFact.js
  src/pages/Homepage.css
  src/pages/Quizcategories.css
Labels: style

#86 style: fix styling issue by readding culture icon
  public/culture.svg
Labels: style

#89 bug: fix the build error with score calculation
  src/pages/Resultpage.js
  src/tests/Resultpage.test.js
Labels: bug

#90 style: improve styling of the result page
  src/pages/Resultpage.css
  src/pages/Resultpage.js
Labels: style

#92 chore: update pipeline with cache to speed up the process -issue #18
  .github/workflows/ci-cd.yml
Labels: CI/CD pipeline

#95 style: improve styling of the footer and responsive design of result page -issue #13
  src/pages/Footer.css
  src/pages/Footer.js
  src/pages/Resultpage.css
Labels: style

#96 style: fix result page score message size -issue #13
  src/pages/Resultpage.css
Labels: style

#106 Testing
  src/tests/Homepage.test.js
  src/tests/Quizcategories.test.js
  src/tests/Resultpage.test.js
Labels: mock-testing, Final Testing

#119 Testing #3
  src/tests/OpenaiApi.test.js
  src/tests/Quizpage.test.js
  src/tests/TriviaApi.test.js
  src/utils/openaiApi.js
  src/utils/triviaApi.js
Labels: API testing, mock-testing, Final Testing

#120 Testing #4
  src/tests/Footer.test.js
  src/tests/HelpButton.test.js
Labels: style, Final Testing

#128 chore: add detailed alt texts for images - issue #126
  netlify/functions/budEChatbotReply.js
  netlify/functions/generateQuestions.js
  netlify/functions/getFunFact.js
  netlify/functions/getTriviaQuestions.js
  src/context/QuizContext.js
  src/pages/AboutPage.js
  src/pages/ContactPage.js
  src/pages/Footer.js
  src/pages/Homepage.js
  src/pages/Quizcategories.js
  src/pages/Quizpage.css
  src/pages/Quizpage.js
  src/pages/Resultpage.js
  src/tests/Footer.test.js
  src/tests/Quizcategories.test.js
Labels: documentation, style

#131 Tests Enhancement
  src/tests/Footer.test.js
  src/tests/HelpButton.test.js
  src/tests/Homepage.test.js
  src/tests/OpenaiApi.test.js
  src/tests/Quizcategories.test.js
  src/tests/Quizpage.test.js
  src/tests/Resultpage.test.js
  src/tests/TriviaApi.test.js
Labels: Final Testing

#130 PR(clean_up)
  src/pages/Footer.css
  src/pages/HelpButton.css
  src/pages/Homepage.css
  src/pages/Quizcategories.css
  src/pages/Quizpage.css
  src/pages/Resultpage.css
  src/pages/StaticPage.css
Labels: style

#132 chore: remove console.logs and warnings and add comments to quiz context file
  src/context/QuizContext.js
  src/pages/Quizpage.css
Labels: console-warning
