Repository CMPT-276-SPRING-2025/final-project-11-stars, pull requests merged in 2025-03, with the labels that each got.

#40 Functionality for selecting and displaying image-based quizzes
  src/context/QuizContext.js
  src/pages/Quizpage.js
Labels: API

#41 Image-based question - Trivia API feature
  src/context/QuizContext.js
  src/pages/Quizpage.css
  src/pages/Quizpage.js
Labels: API, style

#42 fix: add state management functionality to avoid attempting to fetch …
  src/pages/Quizcategories.js
Labels: bug

#46 Chatbot
  src/context/QuizContext.js
  src/pages/Quizpage.css
  src/pages/Quizpage.js
Labels: enhancement, API, API testing, style

#51 deploy: move API calls to Netlify functions for deployment -issue #18
  netlify/functions/budEChatbotReply.js
  netlify/functions/generateQuestions.js
  netlify/functions/getFunFact.js
  netlify/functions/getTriviaQuestions.js
  src/context/QuizContext.js
  src/pages/Quizpage.js
Labels: Deployment

#52 bug: fix the issue with generateQuestions netlify function - issue #18
  netlify/functions/generateQuestions.js
Labels: bug, Deployment

#53 chore: install netlify-cli in order to test locally - issue #18
  .gitignore
Labels: Deployment

#54 feat: update the .yml file to include deployment via Netlify - issue #18
  .github/workflows/ci-cd.yml
  .github/workflows/deploy.yml
  src/App.test.js
Labels: Deployment, CI/CD pipeline

#58 Tests
  src/tests/Resultpage.test.js
Labels: mock-testing, state
